/** Vietnamese STAR_DETAIL long-form (US-018 / Decision 0002 Option A). */

import type { StarDetailFields } from './star-detail.zh';

export const STAR_DETAIL_VI: Record<string, StarDetailFields> = {
  '紫微': {
    niHaixia: 'Thầy Nghê cho rằng Tử Vi là hoàng đế tinh; người tọa Mệnh cung có khí cô ngạo, thích ở một mình, không thích bị người quản. Tử Vi cần Tả Phụ Hữu Bật kẹp mới phát huy khí chất đế vương; không thì chỉ là cô quân, giàu mà không quý. Tử Vi ở cung Thìn/Tuất tốt nhất, với Thiên Phủ thành cục song tinh, tài quan song mỹ, có thể xuất tướng nhập tướng. Tử Vi sợ nhất Hỏa Tinh, Linh Tinh, Kình Dương, Đà La đồng cung; thêm sát thì cô quý, có quyền mà không có tài.',
    classical: 'Cổ quyết:「Tử Vi đế tọa lâm mệnh chủ tôn quý, thống lĩnh chúng tinh, tọa mệnh chủ quyền uy hiển đạt.」Nam Bắc Sơn Nhân chú:「Tử Vi thủ mệnh ở Thìn vị, tài quan song mỹ, xuất tướng nhập tướng, vị chí tam công; Tý cung an mệnh, phú quý không bền, về sau không đẹp.」',
    bestPalace: 'Cung Mệnh (Thìn/Tuất), Cung Quan Lộc',
    worstPalace: 'Cung Tật Ách, Cung Phu Thê',
    career: 'Chính giới, tầng quản lý, tự lập nghiệp; khí chất đế vương trời ban, hợp vị trí lãnh đạo một mình đảm đương',
    relationship: 'Tình cảm bị động, lòng tự trọng mạnh, cần đối phương chủ động; có khuynh hướng cô độc, kết hôn muộn thì cát',
    wealth: 'Tài vận ổn định, thủ thành mạnh hơn tấn thủ; vị Thìn/Tuất tài quan song mỹ, rất hợp đầu tư tích lũy',
    health: 'Thuộc thổ, chú ý tỳ vị, hệ tiêu hóa. Kỵ quá lao, nên giữ giờ giấc đều',
  },
  '天机': {
    niHaixia: 'Thầy Nghê nói Thiên Cơ là tham mưu tinh, tinh thông minh nhất, nhưng thông minh lộ ra thì hại thân. Thiên Cơ hóa kỵ phiền phức nhất — thông minh phản bị thông minh lầm. Thiên Cơ thuộc mộc, thiện biến linh động; ở Mệnh cung tư duy nhanh nhưng thường đa mưu thiếu quyết, cần rời quê hương xa hành mới phát triển; ứng sự cơ biến, tùy cơ ứng biến là đặc chất lớn nhất.',
    classical: 'Cổ quyết:「Vì nhân sinh tinh hoạt, tự thích kinh doanh; Thiên Cơ tinh thuộc mộc, thương mãi đều nhiều cơ kiến, ly tông tất xa thân, cơ mưu tất viễn ly thân.」Nam Bắc Sơn Nhân chú:「Thiên Cơ cư miếu vượng địa, chủ tinh minh, thiện hoạch định; cư hãm địa thì ảm đạm, ai cũng theo thương làm nghề.」',
    bestPalace: 'Cung Mệnh (vị Mão), Cung Quan Lộc',
    worstPalace: 'Cung Phu Thê',
    career: 'Chuyên gia kỹ thuật, mưu sĩ, nghiên cứu, IT, hoạch định; dùng óc hơn dùng tay, hợp ly hương phát triển',
    relationship: 'Tình cảm đa biến, ý nghĩ quá nhiều, khó chuyên nhất; nên kết hôn muộn, sau hôn cần học buông tư lự',
    wealth: 'Kiếm tiền bằng trí tuệ và kỹ năng, không giỏi thủ tài; lấy chuyên môn kỹ thuật làm nghề thì tài vận ổn',
    health: 'Thuộc mộc, chú ý can mật, hệ thần kinh. Tư tâm nặng dễ mất ngủ, nên tập tĩnh tâm thiền',
  },
  '太阳': {
    niHaixia: 'Thầy Nghê cho rằng Thái Dương là tinh đại nam tử chủ nghĩa; từ Mão đến Ngọ nhập miếu, quang minh chính đại; sau Ngọ dần lạc hãm. Người Thái Dương tọa mệnh khái khái thích thể diện; nam mệnh hợp, nữ mệnh quá mạnh. Thái Dương đại diện cha và trưởng bối; ở Mệnh cung tính hướng ngoại khai lãng, thích được mọi người nhìn thấy, rất hợp công chức hoặc sự nghiệp công chúng. Lạc hãm trước cần sau lười, cô quả lao lục.',
    classical: 'Cổ quyết:「Thái Dương cư Ngọ nhập miếu, quang huy đại phóng, chủ quý hiển, nam mệnh tối cát; lạc hãm thì cô quả lao lục, trước cần sau lười.」Nam Bắc Sơn Nhân chú:「Thái Dương ở cung Ngọ thủ mệnh, tài quan song mỹ, xuất tướng nhập tướng; Thìn vị an mệnh, trung niên tài quan biến mỹ, Ất niên sinh gặp hung cũng đại lợi.」',
    bestPalace: 'Cung Mệnh (Mão đến Ngọ), Cung Quan Lộc',
    worstPalace: 'Cung Phu Thê (nữ mệnh), Cung Tật Ách',
    career: 'Công chức, chính giới, quản lý, quan hệ công chúng, giáo dục, truyền thông; thích đứng trước đám đông, hợp sự nghiệp công chúng',
    relationship: 'Nam mệnh duyên tốt nhưng dễ hoa tâm; nữ mệnh độc lập mạnh, hôn nhân cần mài giũa, nên tìm bạn đời ôn nhu thể thiết',
    wealth: 'Tài vận nhờ nỗ lực, khái khái hay thí, không giỏi tích lũy; nhập miếu tài vận thịnh, lạc hãm tài vận lên xuống',
    health: 'Thuộc hỏa, chú ý tim, mắt. Lạc hãm dễ quá lao, cần nghỉ đủ',
  },
  '武曲': {
    niHaixia: 'Thầy Nghê xem Vũ Khúc là chủ tinh tài bạch, cứng không khuất, sợ nhất cô khắc. Người Vũ Khúc tọa mệnh ý chí kiên định, hợp tài chính quản lý tiền, nhưng tình cảm quá thẳng dễ làm tổn thương người. Vũ Khúc hóa kỵ cần cẩn thận huyết quang bất ngờ. Vũ Khúc ở Thìn Tuất Sửu Mùi được vượng địa; đồng cung Thất Sát thành Tướng Tài cách — cục diện tài cực tốt.',
    classical: 'Cổ quyết:「Vũ Khúc thuộc kim, tính cương cường, một đời nhiều hình khắc; thủ mệnh ở vượng địa, xuất tướng nhập tướng.」Nam Bắc Sơn Nhân chú:「Vũ Khúc thủ mệnh, tam phương tứ chính đều cát, tài quan song mỹ; võ chức thêm Phụ Bật Xương Khúc cũng chủ đại quý; đồng cung Thất Sát là Tướng Tài cách, chủ đại phú.」',
    bestPalace: 'Cung Mệnh (Thìn Tuất Sửu Mùi), Cung Tài Bạch, Cung Quan Lộc',
    worstPalace: 'Cung Phu Thê',
    career: 'Tài chính, quân cảnh, kế toán, kỹ thuật; lực chấp hành cực mạnh, hợp lĩnh vực cần khí phách và quyết đoán',
    relationship: 'Tình cảm thẳng tuột, thiếu thú vị, cần bạn đời ôn nhu bổ sung; kỵ tình cảm cô khắc',
    wealth: 'Tài tinh bản mệnh, tài vận cực mạnh, năng lực quản lý tiền siêu quần; vị Thìn/Tuất tài quan song mỹ',
    health: 'Thuộc kim, chú ý phổi, hô hấp, răng. Hóa kỵ cần phòng huyết quang bất ngờ',
  },
  '天同': {
    niHaixia: 'Thầy Nghê nói Thiên Đồng là phúc tinh, tinh lười nhất. Thiên Đồng tọa mệnh thích hưởng phúc, không thích cạnh tranh, hợp công việc ổn định. Thiên Đồng đồng cung Thiên Lương tốt nhất — hưởng phúc lại có bảo đảm. Thiên Đồng hóa lộc là hóa lộc đẹp nhất, chủ một đời no ấm, vui vẻ nhàn du. Thiên Đồng kỵ lạc hãm — lạc hãm phúc giảm, cần hóa giải với hung tinh.',
    classical: 'Cổ quyết:「Thiên Đồng là phúc đức tinh, tọa mệnh hưởng phúc hữu dư, chủ một đời tiêu dao tự tại, không cần lao khổ.」Nam Bắc Sơn Nhân chú:「Thiên Đồng thủ mệnh, tam phương không sát, một đời vui vẻ, áo cơm sung túc; thêm cát tinh thì phú quý song toàn, người ôn hòa, nhiều nhân duyên.」',
    bestPalace: 'Cung Mệnh, Cung Phúc Đức',
    worstPalace: 'Cung Quan Lộc',
    career: 'Dịch vụ, giải trí, ẩm thực, văn nghệ; môi trường nhẹ vui hợp nhất, kỵ cạnh tranh áp lực cao',
    relationship: 'Tình cảm ôn hòa, không chủ động, dễ bị động tiếp nhận; hôn nhân khá ổn, tính tùy hòa dễ gần',
    wealth: 'Tài vận không nổi bật, dựa lương ổn định, không giỏi đầu cơ; no ấm nhưng khó đại phú',
    health: 'Thuộc thủy, chú ý thận, bàng quang. Thể chất yếu hơn, nên vận động vừa phải, giữ tâm thái nhẹ',
  },
  '廉贞': {
    niHaixia: 'Thầy Nghê cho rằng Liêm Trinh là thứ đào hoa, tài hoa ngang trời nhưng tình cảm phức tạp. Liêm Trinh hóa kỵ rất hung — kiện tụng, lao ngục, tai nạn. Liêm Trinh đồng cung Thiên Tướng hóa hung thành cát, thành cách Hành chính Ấn thụ. Liêm Trinh ngũ hành thuộc hỏa, tính cương liệt, một đời nhiều thăng trầm, tài nghệ xuất chúng; giữ chính không tà thì thành đại khí.',
    classical: 'Cổ quyết:「Liêm Trinh là thứ đào hoa, tài hoa ngang trời, tình cảm nhiều sóng gió; Liêm Tướng đồng cung, hóa hung thành cát, thành cách Hành chính Ấn thụ, nắm quyền bính.」Nam Bắc Sơn Nhân chú:「Liêm Trinh thủ mệnh, gặp cát tinh thì tài hoa xuất chúng; hóa kỵ thì kiện tụng vướng thân, chủ huyết quang, cần phòng.」',
    bestPalace: 'Cung Quan Lộc (phối Thiên Tướng), Cung Mệnh (khi hóa lộc)',
    worstPalace: 'Cung Mệnh (khi hóa kỵ), Cung Phu Thê',
    career: 'Nghệ thuật, giải trí, luật, công chức (phối Thiên Tướng); tài nghệ xuất chúng, nên giữ chính nghiệp mới lâu',
    relationship: 'Đào hoa nhiều, tình cảm phức tạp, dễ gặp tranh chấp tình cảm; nên kết hôn muộn, chọn bạn đời vững chắc',
    wealth: 'Tài vận lên xuống, kiếm tiền bằng tài nghệ; hóa kỵ phòng tranh chấp tài chính và rủi ro pháp lý',
    health: 'Thuộc hỏa, chú ý tim, máu, gan. Hóa kỵ phòng tai nạn và phẫu thuật, lưu ý huyết quang',
  },
  '天府': {
    niHaixia: 'Thầy Nghê nói Thiên Phủ là tài khố tinh, tinh thủ thành — không chủ động phát tài nhưng giữ được của. Người Thiên Phủ tọa mệnh vững trọng bảo thủ; nữ mệnh tốt nhất, năng vượng phu hưng gia. Thiên Phủ thích nhất đồng cung hoặc đối chiếu Tử Vi, thành cục song tinh, tài quan song mỹ. Thiên Phủ sợ Không Kiếp kẹp — thấy Không Kiếp thì tài khố cạn đáy, giữ không được tài.',
    classical: 'Cổ quyết:「Thiên Phủ là tài khố tinh, thủ mệnh vững trọng bảo thủ, chủ tích tài vượng gia; nữ mệnh gặp thì năng vượng phu ích tử, gia đạo hưng long.」Nam Bắc Sơn Nhân chú:「Thiên Phủ thủ mệnh, tam phương cát tụ, tài quan song mỹ, phú quý an khang; gặp Không Kiếp thì tài khố thủng, khó tích tài.」',
    bestPalace: 'Cung Mệnh, Cung Tài Bạch, Cung Điền Trạch',
    worstPalace: 'Cung Thiên Di',
    career: 'Hành chính quản lý, tài chính, bảo hiểm, bất động sản; cầu ổn không mạo hiểm, hợp nghề thủ thành',
    relationship: 'Tình cảm ổn định, lo gia, là bạn đời tốt; chú trọng an toàn gia đình và bảo đảm kinh tế',
    wealth: 'Tài vận cực tốt, năng lực thủ tài mạnh, rất hợp đầu tư tích lũy và bất động sản',
    health: 'Thuộc thổ, chú ý tỳ vị, tiêu hóa. Thể chất vững, nên giữ ăn uống và sinh hoạt đều',
  },
  '太阴': {
    niHaixia: 'Thầy Nghê cho rằng Thái Âm là tài tinh, lợi nữ mệnh; cũng là tinh đại diện mẹ và vợ của nam mệnh. Thái Âm nhập miếu thì tài vận cực tốt; hãm địa thì tài vận bị cản. Thái Âm hóa kỵ cần chú ý vấn đề thân nhân nữ. Thái Âm ở vị Hợi Tý nhập miếu, quang huy toàn chiếu — đại diện nhã nhặn tinh tế, tình cảm phong phú, coi trọng nội tâm và đời sống tinh thần.',
    classical: 'Cổ quyết:「Thái Âm là tài tinh, lợi nữ mệnh; Hợi Tý nhập miếu, quang huy toàn chiếu, tài vận cực thịnh; vị Ngọ lạc hãm, u uất đa tình, tài vận bình.」Nam Bắc Sơn Nhân chú:「Thái Âm thủ mệnh, nhập miếu thì tài phú ưu hậu, nữ mệnh càng tốt; lạc hãm cần nỗ lực mới giàu, tình cảm tinh tế.」',
    bestPalace: 'Cung Mệnh (Hợi Tý), Cung Tài Bạch',
    worstPalace: 'Cung Mệnh (vị Ngọ hãm địa)',
    career: 'Tài chính, ngân hàng, bất động sản, nghệ thuật, giáo dục; tinh tế kiên nhẫn, hợp nghề cần thẩm mỹ và ôn nhu',
    relationship: 'Tình cảm ôn nhu tinh tế, coi trọng cảm nhận nội tâm, cần quan hệ ổn có an toàn cảm',
    wealth: 'Nhập miếu tài vận cực thịnh; lạc hãm cần nỗ lực; quản lý tiền tỉ mỉ, giỏi tích lũy, không giỏi mạo hiểm',
    health: 'Thuộc thủy, chú ý thận, tử cung (nữ mệnh). Dao động cảm xúc ảnh hưởng sức khỏe, nên giữ tâm tình thư thái',
  },
  '贪狼': {
    niHaixia: 'Thầy Nghê nói Tham Lang là tinh đa tài đa nghệ nhất, đào hoa nặng nhất. Tham Lang hóa lộc nhập mệnh thì khí chất tỏa sáng, người thấy người yêu. Tham Lang thuộc tinh muộn phát — trung niên sau mới thật phát đạt. Tham Lang ở vị Dần Thân nhập miếu tốt nhất — đào hoa thịnh, tài nghệ siêu quần; hóa lộc sau tài vận đại phát, nhưng nếu gặp Không Kiếp một đời nhiều sóng gió, khó tụ tài.',
    classical: 'Cổ quyết:「Tham Lang phát phúc hanh thông, đa tài đa nghệ, đào hoa nặng nhất; nhưng khó qua ba mươi tuổi, muộn phát đông. Lạc hãm gặp sát phản cát — lý lạc hãm của Tham Lang.」Nam Bắc Sơn Nhân chú:「Tham Lang thủ mệnh, gặp cát thì phúc lộc đa thọ, phát phúc hanh thông; nhưng về lâu không được thiện chung, nên tu thân dưỡng đức mới thiện chung.」',
    bestPalace: 'Cung Mệnh (hóa lộc), Cung Phúc Đức, Cung Thiên Di',
    worstPalace: 'Cung Tật Ách',
    career: 'Nghệ thuật, giải trí, quan hệ công chúng, bán hàng, phong thủy ngũ thuật; dựa nhân mạch và tài nghệ, kiểu đa tài đa nghệ',
    relationship: 'Đào hoa cực thịnh, tình cảm đa nguyên; nên kết hôn muộn, sau hôn cần kiềm chế đào hoa mới đầu bạc cùng nhau',
    wealth: 'Kiếm tiền bằng nhân mạch và tài nghệ; tài vận trung–vãn niên mới ổn; hóa lộc sau nguồn tài rộng, sớm niên nên thủ vững',
    health: 'Thuộc mộc (hàm thủy), chú ý gan, thận. Đào hoa quá thịnh dễ hao tinh lực, nên tiết chế điều dưỡng',
  },
  '巨门': {
    niHaixia: 'Thầy Nghê cho rằng Cự Môn là tinh khẩu thiệt thị phi; nhưng hóa lộc hóa quyền thì chuyển cát, thành cục dựa khẩu tài kiếm tiền. Cự Môn tọa mệnh đa nghi, thiện biện, hợp luật sư, giáo viên, bán hàng. Cự Môn kỵ nhất hóa kỵ — chủ khẩu thiệt thị phi liên tục, thậm chí kiện tụng. Cự Môn ở vị Tý Ngọ khá tốt — khẩu tài tốt, chủ lấy ngôn ngữ lập thân.',
    classical: 'Cổ quyết:「Cự Môn là ám diệu, chủ khẩu thiệt thị phi; hóa lộc quyền thì chuyển thành lấy khẩu tài mưu sinh, chủ phú quý.」Nam Bắc Sơn Nhân chú:「Cự Môn thủ mệnh, gặp hóa lộc quyền, lấy khẩu thiệt làm nghề đại cát; hóa kỵ thì khẩu thiệt liên lụy, kiện tụng vướng thân, cần thận trọng ngôn ngữ.」',
    bestPalace: 'Cung Quan Lộc (hóa lộc quyền), Cung Mệnh (Tý Ngọ)',
    worstPalace: 'Cung Phu Thê, Cung Tật Ách (hóa kỵ)',
    career: 'Luật sư, giáo viên, bán hàng, MC, chuyên gia đàm phán; khẩu tài là năng lực cốt lõi',
    relationship: 'Đa nghi đa lự, dễ nghĩ nhiều; giao tiếp là then chốt hôn nhân, cần chọn bạn đời kiên nhẫn',
    wealth: 'Kiếm tiền bằng khẩu tài và kỹ năng chuyên môn; hóa lộc sau tài vận khá tốt; hóa kỵ phòng tranh chấp tài chính khẩu thiệt liên lụy',
    health: 'Thuộc thủy, chú ý thận, tai, miệng. Đa tư đa lự dễ hại thân, nên học thư giãn giảm áp',
  },
  '天相': {
    niHaixia: 'Thầy Nghê nói Thiên Tướng là ấn thụ tinh, phụ trách hành chính thứ vụ. Người Thiên Tướng tọa mệnh trung quy trung củ, hợp công chức hành chính. Thiên Tướng cần cường tinh phối mới phát huy; một mình tọa mệnh khá bình. Thiên Tướng thích nhất Liêm Trinh kèm — thành Liêm Tướng cách, nắm đại quyền hành chính; sợ nhất Phá Quân đồng cung — thành Hình Kỵ Kẹp Ấn cách, chủ hung hiểm.',
    classical: 'Cổ quyết:「Thiên Tướng là ấn thụ tinh, chủ hành chính thứ vụ; Liêm Tướng đồng cung, hóa hung thành cát, nắm đại quyền hành chính.」Nam Bắc Sơn Nhân chú:「Thiên Tướng thủ mệnh, trung quy trung củ, hợp công chức; được Liêm Trinh phối thành trụ cột quốc gia; Phá Quân đồng thủ thì hình khắc khó tránh.」',
    bestPalace: 'Cung Quan Lộc, Cung Mệnh (phối Liêm Trinh)',
    worstPalace: 'Cung Tài Bạch, Cung Mệnh (phối Phá Quân thì Hình Kỵ Kẹp Ấn)',
    career: 'Công chức, hành chính quản lý, thư ký, trợ lý; giỏi vai trò hỗ trợ phụ tá, cần cường tinh dẫn đường',
    relationship: 'Tình cảm ổn định, trung hậu thật thà, là bạn đời tốt, nhưng cần đối phương định hướng',
    wealth: 'Tài vận bình ổn, dựa lương tích lũy, không hợp đầu tư mạo hiểm; quản lý kiểu thủ thành hợp nhất',
    health: 'Thuộc thủy, chú ý thận, hệ bạch huyết. Thể chất trung bình, nên giữ thói quen sinh hoạt đều',
  },
  '天梁': {
    niHaixia: 'Thầy Nghê cho rằng Thiên Lương là âm tinh, bảo vệ người khác, cũng đại diện y dược tôn giáo. Người Thiên Lương tọa mệnh có duyên trưởng bối; sớm niên nhiều gian nan, vãn niên hưởng phúc. Thiên Lương sợ nhất hóa kỵ — đại diện trưởng bối hoặc sức khỏe có vấn đề. Thiên Lương đồng cung Thái Dương tốt nhất — nhật nguyệt tịnh minh, quý nhân tí âm, một đời có quý nhân giúp, cuối được bình an.',
    classical: 'Cổ quyết:「Thiên Lương là âm tinh, chủ tí âm bảo vệ; tọa mệnh có duyên trưởng bối, sớm niên chịu rèn, vãn niên hưởng thanh phúc.」Nam Bắc Sơn Nhân chú:「Thiên Lương thủ mệnh, cần gặp cát tinh mới phát đạt; gặp Thái Dương đồng cung, nhật nguyệt tịnh minh, chủ quý hiển, một đời nhiều quý nhân giúp.」',
    bestPalace: 'Cung Mệnh, Cung Phụ Mẫu, Cung Phúc Đức',
    worstPalace: 'Cung Mệnh (khi hóa kỵ), Cung Tài Bạch',
    career: 'Y tế, tôn giáo, luật, công tác xã hội, từ thiện; thích giúp người, có tâm tí âm chúng sinh',
    relationship: 'Tình cảm thường với người chênh lệch tuổi lớn, hoặc duyên đến muộn; cần kiên nhẫn chờ mới được lương duyên',
    wealth: 'Tài vận nhờ quý nhân giúp; sớm niên tài kém, vãn niên tài mới vững; nên thủ không nên xung',
    health: 'Thuộc thổ, chú ý tỳ vị, xương. Cần coi trọng bảo dưỡng sức khỏe tuổi già, nên phòng sớm điều dưỡng',
  },
  '七杀': {
    niHaixia: 'Thầy Nghê nói Thất Sát là tướng quân tinh, quả quyết xung lực mạnh nhưng có tính cô khắc. Thất Sát tọa mệnh phải có phụ tinh hóa giải tính cô, không thì lục thân duyên mỏng. Thất Sát đồng cung Vũ Khúc là Tướng Tài cách — cực tốt. Thất Sát sợ nhất Trúc La Tam Hạn (Dương Đà Hỏa Linh đồng chiếu) — chủ đại hung, cần phòng tai nạn. Thất Sát hóa lộc phản cát, có thể thành đại tướng chi tài.',
    classical: 'Cổ quyết:「Thất Sát là tướng quân tinh, quả quyết xung lực mạnh; thủ mệnh tính cô khắc nặng, lục thân duyên mỏng.」Nam Bắc Sơn Nhân chú:「Thất Sát thủ mệnh, tam hợp cát tụ thì đại quý; gặp Trúc La Tam Hạn (Dương Đà Hỏa Linh), chủ đại hung, phòng tai nạn, phòng hình khắc.」',
    bestPalace: 'Cung Mệnh (có phụ tinh), Cung Quan Lộc',
    worstPalace: 'Cung Phu Thê, Cung Phụ Mẫu',
    career: 'Quân cảnh, khởi nghiệp, giao dịch tài chính, lĩnh vực một mình đảm đương; cần quyết đoán nhanh và khí phách',
    relationship: 'Tình cảm cô khắc, khó tìm bạn đời phù hợp; cần đối tượng bao dung cá tính mạnh, nên kết hôn muộn',
    wealth: 'Tài vận dao động lớn, có cơ hội đại phú cũng có đại khởi đại lạc; đồng cung Vũ Khúc thành Tướng Tài cách đại quý',
    health: 'Thuộc kim, chú ý phổi, đại tràng. Tính tình cấp táo dễ hại thân, nên học kiểm soát cảm xúc và tu thân',
  },
  '破军': {
    niHaixia: 'Thầy Nghê nói Phá Quân là tinh phá cũ lập mới nhất, cũng là một trong những tinh cô khắc nhất. Phá Quân hóa lộc sau mới tốt — đại diện phá rồi mới lập. Phá Quân tọa mệnh lục thân duyên mỏng nhưng năng lực khai sáng cực mạnh. Phá Quân rất hợp cải cách, sáng tạo; hóa lộc thì tài vận chuyển thịnh — một phá một lập, cuối thành tựu sự nghiệp.',
    classical: 'Cổ quyết:「Phá Quân là tinh phá cũ lập mới nhất, tọa mệnh cô khắc, lục thân duyên mỏng, nhưng năng lực khai sáng cực mạnh; hóa lộc sau phá rồi lập, có thể thành đại nghiệp.」Nam Bắc Sơn Nhân chú:「Phá Quân thủ mệnh, một đời nhiều sóng gió; hóa lộc thì phá tài rồi mới tái dựng, tài vận cuối chuyển tốt, chủ thành tựu vãn niên.」',
    bestPalace: 'Cung Quan Lộc (hóa lộc), Cung Thiên Di',
    worstPalace: 'Cung Phu Thê, Cung Phụ Mẫu',
    career: 'Sự nghiệp khai sáng, quân cảnh, cải cách, quản lý biến đổi; hợp việc tiên phong không ngừng mở lĩnh vực mới',
    relationship: 'Tình cảm nhiều sóng gió, ly hợp bất định, lục thân duyên mỏng; cần chọn bạn đời độc lập và bao dung mạnh',
    wealth: 'Tài vận lên xuống lớn; hóa lộc sau tài vận chuyển tốt; thủ thành thì tài lùi, cần liên tục khai sáng cục mới mới tích tài',
    health: 'Thuộc thủy, chú ý thận, bàng quang, hệ sinh sản. Thể chất lên xuống, nên giữ thói quen vận động đều',
  },
};
